### ISSUE TITLE
ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by ilexpl01** [serek4/node-red-sofar-ktl-x-request#7]
Hi,

Subflow is running 99% fine with some errors as below:

30 Jul 14:38:08 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 70. Received 83
30 Jul 14:54:04 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 77. Received 83
30 Jul 14:57:05 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 18. Received 83
30 Jul 14:58:04 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 56. Received 83
30 Jul 14:58:15 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 26. Received 83
30 Jul 15:06:45 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 74. Received 83
30 Jul 15:07:15 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 28. Received 83
30 Jul 15:08:01 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 51. Received 83
30 Jul 15:09:31 - [error] [function:check frame] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 42. Received 83

Anything can be done with that ?

**Comment by serek4** [comment]
check [this subflow](https://github.com/serek4/node-red-sofar-ktl-x-request/blob/dev-issue_7/sofar-KTL-x-request.json) from dev-issue_7 branch.
 I added too short data handling and some node red warnings logs.

**Comment by ilexpl01** [comment]
subflow imported. Will let You know how does it work tomorrow - thx :)

**Comment by serek4** [comment]
try [it](https://github.com/serek4/node-red-sofar-ktl-x-request/blob/dev-issue_7/sofar-KTL-x-request.json) now.

**Comment by ilexpl01** [comment]
Tomorrow. We have got night in Poland right now 🤪

**Comment by ilexpl01** [comment]
31 Jul 08:47:45 - [warn] [function:check frame] data length OK(112)
31 Jul 08:48:15 - [warn] [function:check frame] data length OK(112)
31 Jul 08:48:45 - [warn] [function:check frame] data length OK(112)
31 Jul 08:49:29 - [warn] [function:check frame] data longer than expected
31 Jul 08:49:45 - [warn] [function:check frame] data length OK(112)
31 Jul 08:50:15 - [warn] [function:check frame] data length OK(112)
31 Jul 08:50:50 - [warn] [function:check frame] data length OK(112)
31 Jul 08:51:16 - [warn] [function:check frame] data length OK(112)
31 Jul 08:51:45 - [warn] [function:check frame] data length OK(112)
31 Jul 08:52:15 - [warn] [function:check frame] data length OK(112)
31 Jul 08:52:45 - [warn] [function:check frame] data length OK(112)
31 Jul 08:53:25 - [warn] [function:check frame] data length OK(112)
31 Jul 08:53:55 - [warn] [function:check frame] data length OK(112)
31 Jul 08:54:39 - [warn] [function:check frame] data length OK(112)
31 Jul 08:55:05 - [warn] [function:check frame] data longer than expected
31 Jul 08:55:35 - [warn] [function:check frame] data longer than expected
31 Jul 08:56:06 - [warn] [function:check frame] data length OK(112)
31 Jul 08:56:35 - [warn] [function:check frame] data longer than expected
31 Jul 08:57:17 - [warn] [function:check frame] data length OK(112)
31 Jul 08:57:35 - [warn] [function:check frame] data longer than expected
31 Jul 08:58:05 - [warn] [function:check frame] data length OK(32)
31 Jul 08:58:05 - [warn] [function:check frame] modbus frame too short
31 Jul 08:58:35 - [warn] [function:check frame] data longer than expected
31 Jul 08:59:05 - [warn] [function:check frame] data length OK(112)
31 Jul 08:59:49 - [warn] [function:check frame] data length OK(112)
31 Jul 09:00:06 - [warn] [function:check frame] data longer than expected
31 Jul 09:00:35 - [warn] [function:check frame] data longer than expected
31 Jul 09:01:06 - [warn] [function:check frame] data length OK(112)
31 Jul 09:01:35 - [warn] [function:check frame] data length OK(112)
31 Jul 09:02:21 - [warn] [function:check frame] data length OK(112)
31 Jul 09:02:56 - [warn] [function:check frame] data length OK(112)
31 Jul 09:03:37 - [warn] [function:check frame] data longer than expected
31 Jul 09:03:55 - [warn] [function:check frame] data length OK(112)
31 Jul 09:04:25 - [warn] [function:check frame] data length OK(112)
31 Jul 09:04:57 - [warn] [function:check frame] data length OK(112)
31 Jul 09:05:25 - [warn] [function:check frame] data length OK(112)
31 Jul 09:06:16 - [warn] [function:check frame] data length OK(112)
31 Jul 09:06:25 - [warn] [function:check frame] data length OK(50)
31 Jul 09:06:25 - [warn] [function:check frame] wrong modbus frame length
31 Jul 09:06:55 - [warn] [function:check frame] data length OK(112)
31 Jul 09:07:32 - [warn] [function:check frame] data length OK(112)
31 Jul 09:07:55 - [warn] [function:check frame] data length OK(112)
31 Jul 09:08:25 - [warn] [function:check frame] data length OK(112)
31 Jul 09:08:56 - [warn] [function:check frame] data length OK(112)
31 Jul 09:09:25 - [warn] [function:check frame] data length OK(112)
31 Jul 09:10:10 - [warn] [function:check frame] data length OK(112)
31 Jul 09:10:25 - [warn] [function:check frame] data length OK(112)
31 Jul 09:10:56 - [warn] [function:check frame] data length OK(112)
31 Jul 09:11:26 - [warn] [function:check frame] data length OK(112)
31 Jul 09:11:55 - [warn] [function:check frame] data length OK(112)
31 Jul 09:12:42 - [warn] [function:check frame] data length OK(94)
31 Jul 09:12:42 - [warn] [function:check frame] wrong modbus frame length
31 Jul 09:12:55 - [warn] [function:check frame] data length OK(112)
31 Jul 09:13:25 - [warn] [function:check frame] data length OK(112)

at least no error message.

**Comment by serek4** [comment]
You can go inside subflow  to node `check frame` and comment out or remove line 27
```js
node.warn(`data length OK(${frame.length})`);
```
to reduce warnings to only errors.
112 bytes is normal response from inverter, longer frames are probably 2 frames send together, but i just ignore second.
I will probably make some additional edits and update subflow.

**Comment by ilexpl01** [comment]
> You can go inside subflow to node `check frame` and comment out or remove line 27
> 
> ```js
> node.warn(`data length OK(${frame.length})`);
> ```
> 
> to reduce warnings to only errors. 112 bytes is normal response from inverter, longer frames are probably 2 frames send together, but i just ignore second. I will probably make some additional edits and update subflow.

I'll be happy to test it.
